const products = [
  {
     _id:'1',
    name: 'Airpods Wireless Bluetooth Headphones',
   image: '/images/airpods.jpg',
    description:
      'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
    brand: 'Apple',
    category: 'Electronics',
    price: '20000',
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id:'2',
    name: 'iPhone 13 Pro 256GB Memory',
     image: '/images/phone.jpg',
    description:
      'Introducing the iPhone 13 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
    brand: 'Apple',
    category: 'Electronics',
    price: 100000,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id:'3',
    name: 'Cannon EOS 80D DSLR Camera',
   image: '/images/camera.jpg',
    description:
      'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
    brand: 'Cannon',
    category: 'Electronics',
    price: 80000,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id:'4',
    name: 'Sony Playstation 5',
 image: '/images/playstation.jpg',
    description:
      'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
    brand: 'Sony',
    category: 'Electronics',
    price: 50000,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id:'5',
    name: 'Logitech G-Series Gaming Mouse',
   image: '/images/mouse.jpg',
    description:
      'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
    brand: 'Logitech',
    category: 'Electronics',
    price: 10000,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id:'6',
    name: 'Amazon Echo Dot 3rd Generation',
    image: '/images/alexa.jpg',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    brand: 'Amazon',
    category: 'Electronics',
    price: 8000,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },{
    _id: '7',
    name: 'Samsung Galaxy S21 Ultra',
    image: '/images/samsung.jpg',
    description: 'The Samsung Galaxy S21 Ultra is a flagship smartphone with a powerful camera system, stunning display, and top-notch performance.',
    brand: 'Samsung',
    category: 'Electronics',
    price: 1200,
    countInStock: 5,
    rating: 4.8,
    numReviews: 18,
  },{
    _id: '8',
  name: 'Samsung 55" QLED TV',
  image: '/images/samsunga-qled.jpg',
  description: 'Quantum HDR powered by HDR10+ for incredible color and clarity. Real Game Enhancer+ optimizes settings for minimal lag and smooth gameplay. Quantum Processor 4K for enhanced picture quality.',
  brand: 'Samsung',
  category: 'Electronics',
  price: 80000,
  countInStock: 8,
  rating: 4.6,
  numReviews: 15}, 
  {
    _id: '9',
    name: 'iphone X',
    image: '/images/iphone_x.jpg',
    description: 'Powerful smartphone with AI camera and fast processor.',
    brand: 'XYZ',
    category: 'Electronics',
    price: 1200,
    countInStock: 25,
    rating: 4.8,
    numReviews: 20,
  },
  {
  _id: '10',
    name: 'Sony Wireless Headphone Pro',
    image: '/images/wireless.jpg',
    description: 'High-quality wireless headphones with noise cancellation.',
    brand: 'AudioTech',
    category: 'Electronics',
    price: 150,
    countInStock: 30,
    rating: 4.5,
    numReviews: 18,
  },


];

export default products;
